### ISSUE TITLE
一起玩麽？

### ISSUE THREAD

**Issue by jin10086** [build2last/NCspider#1]
玩python已經有1年了吧，最開始也是因爲爬蟲而加入的。
但是前端很亂，我覺得我們可以一起進步啊。
我做了個豆瓣爬蟲，具體你可以看wuaics.cn
現在還有一個爬蟲在爬知乎。
如果有興趣的話，請聯係我

**Comment by build2last** [comment]
My pleasure

**Comment by build2last** [comment]
不过我还在念本科，大三也算比较忙，虽然不能经常在线，不过我会持续关注你的。前端的话可以借助bootstrap来帮忙，我一般周末做一些开发
:)

**Comment by kimg1234** [comment]
bootstrap 我也用不好---
咱们加个微信吧
我的: ai1019855680

**Comment by kimg1234** [comment]
@build2last  
bootstrap 我也用不好---
咱们加个微信吧
我的: ai1019855680
